In [16]:
# assignment
# strings
data = 'hello world'

print (data[0])

print (len(data))

print (data)

h
11
hello world


In [17]:
# numbers
value = 123.1
print (value)

value = 10 
print (value)

123.1
10


In [18]:
# boolean
a = True
b = False
print (a,b)

(True, False)


In [19]:
# multiple assignment
a, b, c = 1, 2, 3
print (a,b,c)

(1, 2, 3)


In [20]:
# no value
a = None
print (a)

None


In [22]:
# flow control
# if-then-else
value = 99
if value == 99:
    print ('That is fast.')
elif value > 200:
    print ('That is too fast.')
else:
    print ('That is safe.')

That is fast.


In [23]:
# for loop
for i in range (10):
    print (i)

0
1
2
3
4
5
6
7
8
9


In [24]:
# while loop
i = 0
while i < 10:
    print (i)
    i += 1

0
1
2
3
4
5
6
7
8
9


In [25]:
# data structures
# tuples
a = (1, 2, 3)
print (a)

(1, 2, 3)


In [26]:
# lists
mylist = [1, 2, 3]
print ('Zeroth Value: %d' % mylist[0])
mylist.append(4)
print ('List Length: %d' % len(mylist))
for value in mylist:
    print(value)


Zeroth Value: 1
List Length: 4
1
2
3
4


In [28]:
# dictionary
mydict = {'a': 1, 'b': 2, 'c': 3}
print("A value: %d" % mydict['a']) 
mydict['a'] = 11
print("A value: %d" % mydict['a']) 
print("Keys: %s" % mydict.keys()) 
print("Values: %s" % mydict.values()) 
for key in mydict.keys():
  print(mydict[key])

A value: 1
A value: 11
Keys: ['a', 'c', 'b']
Values: [11, 3, 2]
11
3
2


In [29]:
# Sum function
def mysum(x, y):
  return x + y
# Test sum function
result = mysum(1, 3)
print(result)

4


In [30]:
# Numpy
# define an array
import numpy
mylist = [1, 2, 3]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)

[1 2 3]
(3,)


In [31]:
# access values
import numpy
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)
print("First row: %s" % myarray[0])
print("Last row: %s" % myarray[-1])
print("Specific row and col: %s" % myarray[0, 2])
print("Whole col: %s" % myarray[:, 2])

[[1 2 3]
 [3 4 5]]
(2, 3)
First row: [1 2 3]
Last row: [3 4 5]
Specific row and col: 3
Whole col: [3 5]


In [32]:
# arithmetic
import numpy
myarray1 = numpy.array([2, 2, 2])
myarray2 = numpy.array([3, 3, 3])
print("Addition: %s" % (myarray1 + myarray2))
print("Multiplication: %s" % (myarray1 * myarray2))

Addition: [5 5 5]
Multiplication: [6 6 6]
